# Generated by Django 5.1.6 on 2025-03-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book details'), ('can_create', 'Can add new book'), ('can_edit', 'Can edit book details'), ('can_delete', 'Can delete book')]},
        ),
    ]
